name: "Pull Request"
on: pull_request_target
jobs:
  pr-check:
    name: "Pull Request Check"
    uses: mParticle/mparticle-workflows/.github/workflows/android-kit-pull-request.yml@6e3f30e47a443634cdd3b22b4af4b46c88d515ed